language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: TRiBpCeJjpLue4+TDcJ7Lzgux6ZGvw5TSosajUrEo/wi+XLcIrzK57ZmzZ1HrvnzDP+ckJPLLFZMAAKbiJ9+P043zbwKT2dWtiF66u+8o56pwlw2AOfDyFo/MysrMyVFpzPZ6kJMK634tRE6DZcPPYf06gN/5gIY8L3/VwH8T1io+Dy72PL62bTY65xmwlNwne+yMjPsOuHb6NEc2d9SUyIu2uhNtm+VAZU4CB+idGMQ/pX0HWVSdTeuUaHRpM7rnKQ4nLgA42KxOGZYOszwf994wWzsRn4ZffYKv79t+tGr39BN/DwNBpue/cJi9KTyVvqYUc03cnCRZJu/h3GviWQ86q5YERTC+CNljKKYLGApcYLjyw8V2gJ5SiL3JGDAaUMW8YalXZZMkhsZm/Yvo8b/RxPpjG0in1IX4WYKM5QmAFMihCoEi4rT46wmdJAylm/J53WsBFLedbwd0h25rcgzoHnMIbtNcH+VEyALaqQH8wBh9FlyPp2nMQh/lU50ZW3fr8ulPZDcBHkM5Gf7mlQon5qZtAXv8a0Iex+MJfnPmsE205haTxThjFU7BIF9YPYgsJ2Egk+36/EgCBojFS678wVn0OMfbsb7TwzJrNvm7SCo4jWuEwbgnLaAxuYj8sC4ULcG34BBryoAtWILUJmN3OTZWq0wL1lM+0CA2Zs=
  app: sleepy-woodland-14984
  on:
    repo: rosaxny/blog-posts
