language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Tmo4uyupreJfLn4Aa4H4OBsU+ZtU8IO5NAmR37QvbqUDTH7zmoemfhAirpxTuOpiJM4aWZtJjLMPqNyy4esd7rQMir1jR8KsOiFQqj82ApiY6hbW1sWaGSz/3BQhAIRq7NM0B9PuADvsgpP3eZNRK/ZFpM0cs60UwJ3X0H8dFQKNO2vSj7gOVNb9gKUy10t/U1Fu3NHL8Wzz8kNGMr+CRv51sSAim6s49iTfllAckx13/DTIg/W/ueoFN7DGAsk19GtxfvekDCXO2rhqpnnmUlKpIlnroVRUlB5T5mtK6B216rveVZ7ieQTwgPOPug/Js014+aEGrTfcInNNxlrdz136tdsESOyALDLfu5eeF8atj1nouCY0LNLL/y7f60X6VyLe4TQVFdEAttLCVmFL7hTWxpCpvkHHaojKhIKLpaJY60bqh/R6UkEbCvVaw/1PdoseFNDFw/vDE+ojD7uriRxPYmkmRP/dYhXoUJPaQ6E+iFfMLRw4Lmiuhiwx5fYmLu0RIdzBUtuj8PUyN04XWD8aTjpnsplT71l1avw58gwB8QZNbI5sm3wqQ9uxsGB95OtzBGgOqj/INoCyM8XRWNARFkZ94N7zGQoxOHMaWpoSHeBAckjyLtRq9gsxzjcwP9ExuP9hA2/HHZyuyrlSO8Biw/f3vH8tKW592B4/mjc=
  app: sleepy-caverns-20978
  on:
    repo: rosaxny/blog-posts
